Repository goorung/Gitodo, pull requests merged in 2024-05, with the labels that each got.

#19 [Feature] 삭제된 레포지토리 테이블뷰 추가
  Gitodo/Sources/MainViewController.swift
  Gitodo/Sources/RepositorySettings/RepositoryCell.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsView.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewController.swift
  Gitodo/Sources/RepositorySettings/SelectedRepositoryCell.swift
Labels: ✨ enhancement

#20 [Feature] 레포지토리 정보 뷰 수정
  Gitodo/Sources/Helpers/PaletteColor.swift
  Gitodo/Sources/RepositoryInfo/PaletteColorCell.swift
  Gitodo/Sources/RepositoryInfo/PaletteColorView.swift
  Gitodo/Sources/RepositoryInfo/RepositoryInfoView.swift
  Package.resolved
  Package.swift
  Project.swift
Labels: ✨ enhancement

#21 [Feature] 이슈 뷰 구현
  Gitodo/Sources/Helpers/Notification+Extension.swift
  Gitodo/Sources/Issue/AssigneeCell.swift
  Gitodo/Sources/Issue/AssigneeCollectionView.swift
  Gitodo/Sources/Issue/IssueCell.swift
  Gitodo/Sources/Issue/IssueTableView.swift
  Gitodo/Sources/Issue/LabelCell.swift
  Gitodo/Sources/Issue/LabelCollectionView.swift
  Gitodo/Sources/IssueInfo/IssueInfoView.swift
  Gitodo/Sources/IssueInfo/IssueInfoViewController.swift
  Gitodo/Sources/MainView.swift
  Gitodo/Sources/MainViewController.swift
  Gitodo/Sources/Model/Issue.swift
  Package.resolved
  Package.swift
  Project.swift
Labels: ✨ enhancement

#22 [Feature] 커스텀 메뉴 추가
  Gitodo/Sources/MainViewController.swift
  Gitodo/Sources/Menu/MenuCell.swift
  Gitodo/Sources/Menu/MenuType.swift
  Gitodo/Sources/Menu/MenuViewController.swift
Labels: ✨ enhancement

#23 [Feature] 투두뷰 기능 추가
  Gitodo/Sources/BaseViewController.swift
  Gitodo/Sources/Helpers/UIViewController+Extensions.swift
  Gitodo/Sources/Main/MainView.swift
  Gitodo/Sources/Main/MainViewController.swift
  Gitodo/Sources/Main/MainViewModel.swift
  Gitodo/Sources/Main/TodoCell.swift
  Gitodo/Sources/Main/TodoCellViewModel.swift
  Gitodo/Sources/RepoCollectionView.swift
  Gitodo/Sources/TodoItem.swift
  Package.resolved
  Package.swift
  Project.swift
Labels: ✨ enhancement

#26 [Feature] 로그인 기능 구현
  Gitodo/Sources/BaseViewController.swift
  Gitodo/Sources/Helpers/UserDefaultsData.swift
  Gitodo/Sources/Issue/AssigneeCollectionView.swift
  Gitodo/Sources/Issue/LabelCollectionView.swift
  Gitodo/Sources/Login/LoginView.swift
  Gitodo/Sources/Login/LoginViewController.swift
  Gitodo/Sources/Main/MainView.swift
  Gitodo/Sources/Main/MainViewController.swift
  Gitodo/Sources/Model/APIData.swift
  Gitodo/Sources/Model/APIManager.swift
  Gitodo/Sources/Model/Issue.swift
  Gitodo/Sources/Model/LoginData.swift
  Gitodo/Sources/Model/LoginManager.swift
  Gitodo/Sources/Model/UserDefaultsManager.swift
  Gitodo/Sources/SceneDelegate.swift
  Project.swift
Labels: ✨ enhancement

#31 [Fix] name conflict 수정
  Gitodo/Sources/Main/MainViewModel.swift
  Gitodo/Sources/Model/MyRepo.swift
  Gitodo/Sources/RepoCollectionView.swift
  Gitodo/Sources/RepositoryInfo/RepositoryInfoViewController.swift
  Gitodo/Sources/RepositoryInfo/RepositoryInfoViewModel.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingViewModel.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsView.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewController.swift
  Gitodo/Sources/TempRepository.swift
  Gitodo/Sources/TodoItem.swift
Labels: 🐛 bug

#32 [Feature] API 연결
  Gitodo/Sources/Helpers/PaletteColor.swift
  Gitodo/Sources/Issue/AssigneeCollectionView.swift
  Gitodo/Sources/Issue/IssueTableView.swift
  Gitodo/Sources/Issue/IssueViewModel.swift
  Gitodo/Sources/Main/MainView.swift
  Gitodo/Sources/Main/MainViewController.swift
  Gitodo/Sources/Main/MainViewModel.swift
  Gitodo/Sources/Model/APIData.swift
  Gitodo/Sources/Model/APIManager.swift
  Gitodo/Sources/Model/MyRepo.swift
  Gitodo/Sources/RepositoryInfo/PaletteColorView.swift
  Gitodo/Sources/RepositoryInfo/RepositoryInfoView.swift
  Gitodo/Sources/RepositoryInfo/RepositoryInfoViewController.swift
  Gitodo/Sources/RepositoryInfo/RepositoryInfoViewModel.swift
  Gitodo/Sources/RepositorySettings/RepositoryCell.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingViewModel.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsView.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewController.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewModel.swift
  Gitodo/Sources/TempRepository.swift
Labels: ✨ enhancement

#35 [Feature] 민감한 정보의 저장 방식 개선
  .gitignore
  Gitodo/Sources/Helpers/Notification+Extension.swift
  Gitodo/Sources/Main/MainViewController.swift
  Gitodo/Sources/Model/APIManager.swift
  Gitodo/Sources/Model/KeychainManager.swift
  Gitodo/Sources/Model/LoginManager.swift
  Gitodo/Sources/Model/UserDefaultsManager.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewController.swift
  Project.swift
Labels: ✨ enhancement, 🛠️ refactoring

#39 [Feature] 로그인 후 처음 접속 시 레포지토리 설정 페이지로 이동
  .gitignore
  Gitodo/Sources/Main/MainViewController.swift
  Gitodo/Sources/Model/UserDefaultsManager.swift
Labels: ✨ enhancement

#40 [Feature] 이슈 목록에서 Pull Request 필터링
  Gitodo/Sources/Issue/IssueViewModel.swift
  Gitodo/Sources/Model/APIData.swift
Labels: ✨ enhancement

#43 [Feature] Realm 연결 및 Todo 기능 추가
  Gitodo/Sources/BaseViewController.swift
  Gitodo/Sources/Main/MainView.swift
  Gitodo/Sources/Main/MainViewController.swift
  Gitodo/Sources/Main/MainViewModel.swift
  Gitodo/Sources/Model/Local/EntityMapping/RepositoryEntity+Mapping.swift
  Gitodo/Sources/Model/Local/EntityMapping/TodoEntity+Mapping.swift
  Gitodo/Sources/Model/Local/LocalRepositoryService.swift
  Gitodo/Sources/Model/Local/LocalTodoService.swift
  Gitodo/Sources/Model/Local/RealmError.swift
  Gitodo/Sources/Model/TodoItem.swift
  Gitodo/Sources/RepoCollectionView.swift
  Gitodo/Sources/RepositorySettings/RepositoryCell.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsView.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewController.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewModel.swift
  Gitodo/Sources/SceneDelegate.swift
  Gitodo/Sources/TempRepository.swift
  Gitodo/Sources/Todo/TodoCell.swift
  Gitodo/Sources/Todo/TodoCellViewModel.swift
  Gitodo/Sources/Todo/TodoView.swift
  Gitodo/Sources/Todo/TodoViewModel.swift
  Package.resolved
  Package.swift
  Project.swift
Labels: ✨ enhancement

#48 [Feature] 로그아웃 기능 구현
  Gitodo/Sources/Main/MainViewController.swift
  Gitodo/Sources/Main/MainViewModel.swift
  Gitodo/Sources/Model/Local/LocalRepositoryService.swift
  Gitodo/Sources/Model/LoginManager.swift
  Gitodo/Sources/SceneDelegate.swift
Labels: ✨ enhancement

#50 [Feature] 레포컬렉션뷰 기능 추가
  Gitodo/Sources/Main/MainView.swift
  Gitodo/Sources/Main/MainViewController.swift
  Gitodo/Sources/Main/MainViewModel.swift
  Gitodo/Sources/Menu/MainMenuType.swift
  Gitodo/Sources/Menu/MenuCell.swift
  Gitodo/Sources/Menu/RepoMenuViewController.swift
  Gitodo/Sources/RepoCollectionView.swift
  Gitodo/Sources/RepositoryInfoCell.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsView.swift
  Gitodo/Sources/RepositoryView.swift
  Gitodo/Sources/SymbolCircleView.swift
  Gitodo/Sources/Todo/TodoCellViewModel.swift
  Package.swift
Labels: ✨ enhancement

#52 [Feature] API 호출 컴포넌트 로딩뷰 추가 및 레포지토리 새로고침 버튼 추가
  .mise.toml
  Gitodo/Sources/BaseViewController.swift
  Gitodo/Sources/Issue/AssigneeCollectionView.swift
  Gitodo/Sources/Issue/IssueTableView.swift
  Gitodo/Sources/Issue/IssueView.swift
  Gitodo/Sources/Issue/IssueViewModel.swift
  Gitodo/Sources/Main/MainView.swift
  Gitodo/Sources/Main/MainViewController.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsView.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewController.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewModel.swift
  Gitodo/Sources/SymbolCircleView.swift
  Gitodo/Sources/Todo/TodoView.swift
  Project.swift
Labels: ✨ enhancement

#60 [Feature] 진동 효과 추가
  Gitodo/Sources/Helpers/UIView+Extension.swift
  Gitodo/Sources/Main/MainView.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsView.swift
  Gitodo/Sources/Todo/TodoView.swift
Labels: ✨ enhancement

#62 [Feature] 위젯 타겟 추가
  Project.swift
  Widgets/RepoListWidget/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Widgets/RepoListWidget/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Widgets/RepoListWidget/Resources/Assets.xcassets/Contents.json
  Widgets/RepoListWidget/Resources/Assets.xcassets/WidgetBackground.colorset/Contents.json
  Widgets/RepoListWidget/Sources/AppIntent.swift
  Widgets/RepoListWidget/Sources/RepoListWidget.swift
  Widgets/RepoListWidget/Sources/RepoListWidgetBundle.swift
  Widgets/RepoTodoWidget/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Widgets/RepoTodoWidget/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Widgets/RepoTodoWidget/Resources/Assets.xcassets/Contents.json
  Widgets/RepoTodoWidget/Resources/Assets.xcassets/WidgetBackground.colorset/Contents.json
  Widgets/RepoTodoWidget/Sources/AppIntent.swift
  Widgets/RepoTodoWidget/Sources/RepoTodoWidget.swift
  Widgets/RepoTodoWidget/Sources/RepoTodoWidgetBundle.swift
Labels: 🪐 build

#63 [Feature] deleted repo 유지
  Gitodo/Sources/Model/Local/LocalRepositoryService.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewController.swift
Labels: ✨ enhancement

#65 [Refactor] issueInfoVC present 속도 개선
  Gitodo/Sources/IssueInfo/IssueInfoView.swift
  Gitodo/Sources/Main/MainViewController.swift
Labels: 🛠️ refactoring

#67 [Feature] GitodoShared 프레임워크 추가 및 AppGroups 설정
  Gitodo.entitlements
  Gitodo/Sources/Issue/AssigneeCollectionView.swift
  Gitodo/Sources/Issue/IssueCell.swift
  Gitodo/Sources/Issue/IssueView.swift
  Gitodo/Sources/Issue/IssueViewModel.swift
  Gitodo/Sources/Issue/LabelCell.swift
  Gitodo/Sources/Issue/LabelCollectionView.swift
  Gitodo/Sources/IssueInfo/IssueInfoView.swift
  Gitodo/Sources/IssueInfo/IssueInfoViewController.swift
  Gitodo/Sources/Main/MainView.swift
  Gitodo/Sources/Main/MainViewController.swift
  Gitodo/Sources/Main/MainViewModel.swift
  Gitodo/Sources/Menu/RepoMenuViewController.swift
  Gitodo/Sources/Model/APIData.swift
  Gitodo/Sources/Model/APIManager.swift
  Gitodo/Sources/Model/Local/LocalRepositoryService.swift
  Gitodo/Sources/Model/Local/LocalTodoService.swift
  Gitodo/Sources/Model/MyRepo.swift
  Gitodo/Sources/RepoCollectionView.swift
  Gitodo/Sources/RepositoryInfo/PaletteColorView.swift
  Gitodo/Sources/RepositoryInfo/RepositoryInfoView.swift
  Gitodo/Sources/RepositoryInfo/RepositoryInfoViewController.swift
  Gitodo/Sources/RepositoryInfo/RepositoryInfoViewModel.swift
  Gitodo/Sources/RepositoryInfoCell.swift
  Gitodo/Sources/RepositorySettings/RepositoryCell.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsView.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewController.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewModel.swift
  Gitodo/Sources/Todo/TodoCellViewModel.swift
  Gitodo/Sources/Todo/TodoView.swift
  Gitodo/Sources/Todo/TodoViewModel.swift
  GitodoShared/Sources/EntityMapping/RepositoryEntity+Mapping.swift
  GitodoShared/Sources/EntityMapping/TodoEntity+Mapping.swift
  GitodoShared/Sources/Model/APIData.swift
  GitodoShared/Sources/Model/MyRepo.swift
  GitodoShared/Sources/Model/PaletteColor.swift
  GitodoShared/Sources/Model/RealmError.swift
  GitodoShared/Sources/Model/TodoItem.swift
  Project.swift
  Widgets/RepoListWidget/Sources/AppIntent.swift
Labels: 🛠️ refactoring

#70 [Feature] 원격에서 삭제된 레포지토리 IssueView message 추가
  Gitodo/Sources/Issue/IssueView.swift
  Gitodo/Sources/Issue/IssueViewModel.swift
  Gitodo/Sources/Main/MainView.swift
Labels: ✨ enhancement

#72 [Fix] 원격에서 삭제된 레포지토리 삭제 시도 시 체크 표시 되는 문제 해결
  Gitodo/Sources/RepositorySettings/RepositoryCell.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsView.swift
Labels: 🐛 bug

#75 [Feature] 다크모드에서의 UI 수정
  Gitodo/Sources/BaseViewController.swift
  Gitodo/Sources/Helpers/UIColor+Extension.swift
  Gitodo/Sources/Issue/AssigneeCollectionView.swift
  Gitodo/Sources/Issue/IssueCell.swift
  Gitodo/Sources/Issue/IssueView.swift
  Gitodo/Sources/Issue/LabelCell.swift
  Gitodo/Sources/Issue/LabelCollectionView.swift
  Gitodo/Sources/Menu/MenuCell.swift
  Gitodo/Sources/Menu/MenuViewController.swift
  Gitodo/Sources/Menu/RepoMenuViewController.swift
  Gitodo/Sources/RepositoryInfo/PaletteColorCell.swift
  Gitodo/Sources/RepositoryInfo/PaletteColorView.swift
  Gitodo/Sources/RepositoryInfo/RepositoryInfoView.swift
  Gitodo/Sources/RepositorySettings/RepositoryCell.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsView.swift
  Gitodo/Sources/Todo/TodoCell.swift
  Gitodo/Sources/Todo/TodoView.swift
Labels: ✨ enhancement

#76 [Feature] 폰트 수정
  Gitodo/Sources/BaseViewController.swift
  Gitodo/Sources/Helpers/UIFont+Extension.swift
  Gitodo/Sources/Issue/IssueCell.swift
  Gitodo/Sources/Issue/IssueView.swift
  Gitodo/Sources/Issue/LabelCell.swift
  Gitodo/Sources/Issue/LabelCollectionView.swift
  Gitodo/Sources/IssueInfo/IssueInfoView.swift
  Gitodo/Sources/Main/MainView.swift
  Gitodo/Sources/Main/MainViewController.swift
  Gitodo/Sources/Menu/MenuCell.swift
  Gitodo/Sources/Menu/RepoMenuViewController.swift
  Gitodo/Sources/RepositoryInfo/RepositoryInfoView.swift
  Gitodo/Sources/RepositorySettings/RepositoryCell.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsView.swift
  Gitodo/Sources/RepositoryView.swift
  Gitodo/Sources/Todo/TodoCell.swift
  Gitodo/Sources/Todo/TodoView.swift
Labels: ✨ enhancement

#78 [Feature] 앱 아이콘 추가 및 로그인 화면 구현
  Gitodo/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Gitodo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Gitodo/Resources/Assets.xcassets/Contents.json
  Gitodo/Sources/Login/LoginView.swift
Labels: ✨ enhancement

#80 [Feature] 네트워크 연결 없을 때 API 호출 처리
  Gitodo/Sources/Issue/IssueView.swift
  Gitodo/Sources/Issue/IssueViewModel.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsView.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewModel.swift
Labels: ✨ enhancement, 🛠️ refactoring

#82 [Feature] 로그인 실패 및 로딩 처리
  .gitmessage.txt
  Gitodo/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Gitodo/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Gitodo/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Gitodo/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Gitodo/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Gitodo/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Gitodo/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Gitodo/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Gitodo/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Gitodo/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Gitodo/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Gitodo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Gitodo/Resources/Assets.xcassets/Contents.json
  Gitodo/Resources/Assets.xcassets/appstore.imageset/Contents.json
  Gitodo/Resources/Assets.xcassets/appstore.imageset/appstore.png
  Gitodo/Resources/Assets.xcassets/loading_1.imageset/Contents.json
  Gitodo/Resources/Assets.xcassets/loading_1.imageset/loading_1.png
  Gitodo/Resources/Assets.xcassets/loading_2.imageset/Contents.json
  Gitodo/Resources/Assets.xcassets/loading_2.imageset/loading_2.png
  Gitodo/Resources/Assets.xcassets/loading_3.imageset/Contents.json
  Gitodo/Resources/Assets.xcassets/loading_3.imageset/loading_3.png
  Gitodo/Resources/Assets.xcassets/loading_4.imageset/Contents.json
  Gitodo/Resources/Assets.xcassets/loading_4.imageset/loading_4.png
  Gitodo/Resources/Assets.xcassets/logo.imageset/Contents.json
  Gitodo/Resources/Assets.xcassets/logo.imageset/logo.png
  Gitodo/Resources/Assets.xcassets/playstore.imageset/Contents.json
  Gitodo/Resources/Assets.xcassets/playstore.imageset/playstore.png
  Gitodo/Sources/Helpers/Notification+Extension.swift
  Gitodo/Sources/Login/LoginView.swift
  Gitodo/Sources/Login/LoginViewController.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewController.swift
  Gitodo/Sources/SceneDelegate.swift
Labels: ✨ enhancement

#83 [Fix] markdownView 잘림 및 레이아웃 수정
  Gitodo/Sources/IssueInfo/IssueInfoView.swift
Labels: 🐛 bug

#85 [Refactor] 앱 타겟(Gitodo) 리팩토링
  Gitodo/Sources/Base/BaseViewController.swift
  Gitodo/Sources/Base/BaseViewModel.swift
  Gitodo/Sources/Helpers/UIViewController+Extensions.swift
  Gitodo/Sources/Issue/AssigneeCell.swift
  Gitodo/Sources/Issue/AssigneeCollectionView.swift
  Gitodo/Sources/Issue/IssueCell.swift
  Gitodo/Sources/Issue/IssueView.swift
  Gitodo/Sources/Issue/IssueViewModel.swift
  Gitodo/Sources/Issue/LabelCell.swift
  Gitodo/Sources/Issue/LabelCollectionView.swift
  Gitodo/Sources/IssueInfo/IssueInfoView.swift
  Gitodo/Sources/IssueInfo/IssueInfoViewController.swift
  Gitodo/Sources/Login/LoginView.swift
  Gitodo/Sources/Login/LoginViewController.swift
  Gitodo/Sources/Main/MainView.swift
  Gitodo/Sources/Main/MainViewController.swift
  Gitodo/Sources/Main/MainViewModel.swift
  Gitodo/Sources/Menu/MainMenuType.swift
  Gitodo/Sources/Menu/MenuCell.swift
  Gitodo/Sources/Menu/MenuViewController.swift
  Gitodo/Sources/Menu/RepoMenuViewController.swift
  Gitodo/Sources/Repository/RepoCollectionView.swift
  Gitodo/Sources/Repository/RepositoryInfoCell.swift
  Gitodo/Sources/Repository/RepositoryView.swift
  Gitodo/Sources/Repository/SymbolCircleView.swift
  Gitodo/Sources/RepositoryInfo/PaletteColorCell.swift
  Gitodo/Sources/RepositoryInfo/PaletteColorView.swift
  Gitodo/Sources/RepositoryInfo/RepositoryInfoView.swift
  Gitodo/Sources/RepositoryInfo/RepositoryInfoViewController.swift
  Gitodo/Sources/RepositorySettings/RepositoryCell.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsView.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewController.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewModel.swift
  Gitodo/Sources/Todo/TodoCell.swift
  Gitodo/Sources/Todo/TodoView.swift
  Gitodo/Sources/Todo/TodoViewModel.swift
Labels: 🛠️ refactoring

#87 [Feature] 레포지토리 컬렉션 뷰 UI 조정
  Gitodo/Sources/Main/MainView.swift
  Gitodo/Sources/Repository/RepoCollectionView.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsView.swift
Labels: ✨ enhancement

#89 [Feature] 문의하기 Github wiki 페이지와 연결
  Gitodo/Sources/Contact/ContactView.swift
  Gitodo/Sources/Contact/ContactViewController.swift
  Gitodo/Sources/Main/MainViewController.swift
Labels: ✨ enhancement

#92 [Fix] 로그아웃 시 레포지토리 설정 false로 변경
  Gitodo/Sources/Main/MainViewController.swift
Labels: 🐛 bug

#94 [Feature] todo updatedAt 항목 추가
  Gitodo/Sources/Model/Local/LocalTodoService.swift
  GitodoShared/Sources/EntityMapping/TodoEntity+Mapping.swift
  Widgets/RepoTodoWidget/Sources/RepoTodoManager.swift
Labels: ✨ enhancement

#95 [Feature] 소소한 수정
  Gitodo/Sources/Main/MainViewController.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewController.swift
  Widgets/RepoListWidget/Sources/RepoListWidget.swift
  Widgets/RepoListWidget/Sources/View/RepoListWidgetEntryView.swift
  Widgets/RepoTodoWidget/Sources/RepoTodoWidget.swift
Labels: ✨ enhancement

#97 [Docs] add privacy manifest file
  Gitodo/Resources/PrivacyInfo.xcprivacy
  GitodoShared/Resources/PrivacyInfo.xcprivacy
  Project.swift
  Widgets/RepoListWidget/Resources/PrivacyInfo.xcprivacy
  Widgets/RepoTodoWidget/Resources/PrivacyInfo.xcprivacy
Labels: 📋 documentation

#99 [Refactor] 앱 및 타겟 이름 변경
  Project.swift
  Widgets/RepoList/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Widgets/RepoList/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Widgets/RepoList/Resources/Assets.xcassets/Contents.json
  Widgets/RepoList/Resources/Assets.xcassets/WidgetBackground.colorset/Contents.json
  Widgets/RepoList/Resources/PrivacyInfo.xcprivacy
  Widgets/RepoList/Sources/Model/RepoListEntry.swift
  Widgets/RepoList/Sources/Model/RepoListWidgetService.swift
  Widgets/RepoList/Sources/RepoListWidget.swift
  Widgets/RepoList/Sources/RepoListWidgetBundle.swift
  Widgets/RepoList/Sources/View/CircularProgressBarView.swift
  Widgets/RepoList/Sources/View/RepoListWidgetEntryView.swift
  Widgets/RepoList/Sources/View/RepoView.swift
  Widgets/RepoTodo/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Widgets/RepoTodo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Widgets/RepoTodo/Resources/Assets.xcassets/Color/Contents.json
  Widgets/RepoTodo/Resources/Assets.xcassets/Color/blueLabel.colorset/Contents.json
  Widgets/RepoTodo/Resources/Assets.xcassets/Color/defaultLabel.colorset/Contents.json
  Widgets/RepoTodo/Resources/Assets.xcassets/Color/greenLabel.colorset/Contents.json
  Widgets/RepoTodo/Resources/Assets.xcassets/Color/pinkLabel.colorset/Contents.json
  Widgets/RepoTodo/Resources/Assets.xcassets/Color/purpleLabel.colorset/Contents.json
  Widgets/RepoTodo/Resources/Assets.xcassets/Color/redLabel.colorset/Contents.json
  Widgets/RepoTodo/Resources/Assets.xcassets/Color/yellowLabel.colorset/Contents.json
  Widgets/RepoTodo/Resources/Assets.xcassets/Contents.json
  Widgets/RepoTodo/Resources/Assets.xcassets/WidgetBackground.colorset/Contents.json
  Widgets/RepoTodo/Resources/PrivacyInfo.xcprivacy
  Widgets/RepoTodo/Sources/RepoTodoManager.swift
  Widgets/RepoTodo/Sources/RepoTodoWidget.swift
  Widgets/RepoTodo/Sources/RepoTodoWidgetBundle.swift
  Widgets/RepoTodo/Sources/RepositoryIntent.swift
  Widgets/RepoTodo/Sources/ToggleStateIntent.swift
  Widgets/RepoTodo/Sources/View/SelectedRepoView.swift
  Widgets/RepoTodo/Sources/View/TodoListView.swift
Labels: 🛠️ refactoring

#101 [Refactor] Privacy Manifests 수정
  Gitodo/Resources/PrivacyInfo.xcprivacy
  GitodoShared/Resources/PrivacyInfo.xcprivacy
  Widgets/RepoList/Resources/PrivacyInfo.xcprivacy
  Widgets/RepoTodo/Resources/PrivacyInfo.xcprivacy
Labels: 🛠️ refactoring

#107 [Feature] README.md 수정
  README.md
Labels: 📋 documentation

#110 [Refactor] 로그인 시 외부 앱으로 이동하지 않도록 변경
  Gitodo/Resources/Assets.xcassets/loading_1.imageset/loading_1.png
  Gitodo/Resources/Assets.xcassets/loading_2.imageset/loading_2.png
  Gitodo/Resources/Assets.xcassets/loading_3.imageset/loading_3.png
  Gitodo/Resources/Assets.xcassets/loading_4.imageset/loading_4.png
  Gitodo/Sources/Login/LoginViewController.swift
Labels: 🛠️ refactoring

#115 [Feature] 레포지토리 설정 뷰 네비게이션 바 아이템 수정
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewController.swift
Labels: ✨ enhancement

#117 [Fix] 토글, 삭제 튕김 해결
  Gitodo/Sources/Todo/TodoCell.swift
  Gitodo/Sources/Todo/TodoView.swift
  Gitodo/Sources/Todo/TodoViewModel.swift
Labels: 🐛 bug

#118 [Feature] 문의하기 로그인 정보 유지
  Gitodo/Sources/AppDelegate.swift
  Gitodo/Sources/Auth/AuthView.swift
  Gitodo/Sources/Auth/AuthViewController.swift
  Gitodo/Sources/Contact/ContactView.swift
  Gitodo/Sources/Extensions/Notification+Extension.swift
  Gitodo/Sources/Extensions/UIColor+Extension.swift
  Gitodo/Sources/Extensions/UIFont+Extension.swift
  Gitodo/Sources/Extensions/UIView+Extension.swift
  Gitodo/Sources/Extensions/UIViewController+Extensions.swift
  Gitodo/Sources/Utils/APIManager.swift
  Gitodo/Sources/Utils/KeychainManager.swift
  Gitodo/Sources/Utils/LoginManager.swift
  Gitodo/Sources/Utils/WebViewPreloader.swift
Labels: ✨ enhancement

#120 [Fix] 마크다운 비었을 떄 처리
  Gitodo/Sources/IssueInfo/IssueInfoView.swift
Labels: 🐛 bug

#122 [Feature] 문의하기 뷰 제스처로 뒤로 가기 허용
  Gitodo/Sources/Contact/ContactView.swift
Labels: ✨ enhancement

#123 [Fix] 투두 완료 튕김 에러 해결
  Gitodo/Sources/Todo/TodoView.swift
  Gitodo/Sources/Todo/TodoViewModel.swift
Labels: 🐛 bug

#124 [Fix] delete error
  Gitodo/Sources/Todo/TodoView.swift
Labels: 🐛 bug
