Repository goorung/Gitodo, pull requests merged in 2024-08, with the labels that each got.

#145 [Fix] 개인 레포지토리 API 엔드포인트 수정
  Gitodo/Sources/Utils/APIManager.swift
Labels: 🐛 bug, ✨ enhancement

#147 [Feature] 페이지네이션 구현
  Gitodo/Sources/Issue/IssueView.swift
  Gitodo/Sources/Issue/IssueViewModel.swift
  Gitodo/Sources/Organization/OrganizationView.swift
  Gitodo/Sources/Organization/OrganizationViewController.swift
  Gitodo/Sources/Organization/OrganizationViewModel.swift
  Gitodo/Sources/Repository/RepositoryView.swift
  Gitodo/Sources/Repository/RepositoryViewController.swift
  Gitodo/Sources/Repository/RepositoryViewModel.swift
  Gitodo/Sources/Utils/APIManager.swift
Labels: ✨ enhancement

#148 [Feature] 완료된 할 일 자동 삭제 기능
  Gitodo/Sources/Base/SelfSizingTableView.swift
  Gitodo/Sources/Extensions/UIFont+Extension.swift
  Gitodo/Sources/Login/LoginViewController.swift
  Gitodo/Sources/Main/MainView.swift
  Gitodo/Sources/Main/MainViewController.swift
  Gitodo/Sources/Main/MainViewModel.swift
  Gitodo/Sources/Menu/CleanupMenuViewController.swift
  Gitodo/Sources/Menu/MenuCell.swift
  Gitodo/Sources/Model/Local/LocalRepositoryService.swift
  Gitodo/Sources/Model/Local/LocalTodoService.swift
  Gitodo/Sources/MyRepoInfo/DeletionOption/DeletionOptionCell.swift
  Gitodo/Sources/MyRepoInfo/DeletionOption/DeletionOptionView.swift
  Gitodo/Sources/MyRepoInfo/DeletionOption/DeletionOptionViewController.swift
  Gitodo/Sources/MyRepoInfo/MyRepoInfoView.swift
  Gitodo/Sources/MyRepoInfo/MyRepoInfoViewController.swift
  Gitodo/Sources/MyRepoInfo/MyRepoInfoViewModel.swift
  Gitodo/Sources/MyRepoInfo/PaletteColorView.swift
  Gitodo/Sources/MyRepoInfo/SelectedOptionView.swift
  Gitodo/Sources/MyRepoInfo/ToggleOptionView.swift
  Gitodo/Sources/Organization/OrganizationView.swift
  Gitodo/Sources/Repository/RepositoryView.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsView.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewController.swift
  Gitodo/Sources/SceneDelegate.swift
  Gitodo/Sources/Todo/TodoView.swift
  Gitodo/Sources/Todo/TodoViewModel.swift
  GitodoShared/Sources/EntityMapping/RepositoryEntity+Mapping.swift
  GitodoShared/Sources/Model/DeletionOption.swift
  GitodoShared/Sources/Model/MyRepo.swift
  Widgets/RepoList/Sources/Model/RepoListWidgetService.swift
  Widgets/RepoTodo/Sources/RepoTodoManager.swift
  Widgets/RepoTodo/Sources/RepoTodoWidget.swift
Labels: ✨ enhancement

#149 버전 2.0.0 배포 준비
  Gitodo/Sources/Base/LoadableView.swift
  Gitodo/Sources/Issue/IssueView.swift
  Gitodo/Sources/Issue/IssueViewModel.swift
  Gitodo/Sources/Organization/OrganizationView.swift
  Gitodo/Sources/Organization/OrganizationViewController.swift
  Gitodo/Sources/Organization/OrganizationViewModel.swift
  Gitodo/Sources/Repository/RepositoryView.swift
  Gitodo/Sources/Repository/RepositoryViewController.swift
  Gitodo/Sources/Repository/RepositoryViewModel.swift
  Gitodo/Sources/Utils/APIManager.swift
Labels: ✨ enhancement

#152 [Docs] 리드미 파일 수정
  Gitodo/Sources/Base/SelfSizingTableView.swift
  Gitodo/Sources/Extensions/UIFont+Extension.swift
  Gitodo/Sources/Main/MainView.swift
  Gitodo/Sources/Main/MainViewController.swift
  Gitodo/Sources/Model/Local/LocalRepositoryService.swift
  Gitodo/Sources/Model/Local/LocalTodoService.swift
  Gitodo/Sources/MyRepoInfo/DeletionOption/DeletionOptionCell.swift
  Gitodo/Sources/MyRepoInfo/DeletionOption/DeletionOptionView.swift
  Gitodo/Sources/MyRepoInfo/DeletionOption/DeletionOptionViewController.swift
  Gitodo/Sources/MyRepoInfo/MyRepoInfoView.swift
  Gitodo/Sources/MyRepoInfo/MyRepoInfoViewController.swift
  Gitodo/Sources/MyRepoInfo/MyRepoInfoViewModel.swift
  Gitodo/Sources/MyRepoInfo/SelectedOptionView.swift
  Gitodo/Sources/MyRepoInfo/ToggleOptionView.swift
  Gitodo/Sources/Organization/OrganizationView.swift
  Gitodo/Sources/Repository/RepositoryView.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsView.swift
  Gitodo/Sources/RepositorySettings/RepositorySettingsViewController.swift
  Gitodo/Sources/SceneDelegate.swift
  GitodoShared/Sources/Model/DeletionOption.swift
  README.md
  Widgets/RepoTodo/Sources/RepoTodoManager.swift
Labels: 📋 documentation
